package:
  name: metawrap-mg
  version: "1.1.3"

source:
  git_url: https://github.com/bxlab/metaWRAP.git

requirements:
  build:

  run:
    - bcftools 1.6
    - biopython 1.69
    - blast 2.7.*
    - bmfilter 3.101
    - bmtagger 3.101
    - bmtool 3.101
    - boost 1.64.0
    - boost-cpp 1.64.0
    - bowtie2 2.3.*
    - brewer2mpl 1.4.1
    - bwa 0.7.15
    - cairo 1.14.8
    - checkm-genome 1.*
    - concoct 1.*
    - fastqc 0.11.5
    - gnutls 3.5.15
    - icu 58.2
    - java-jdk 8.0.92
    - kraken
    - krona 2.7
    - libgfortran-ng 7.2.0
    - libopenblas 0.2.20
    - matplotlib 1.5.1
    - maxbin2 2.2.5
    - megahit 1.1.2
    - metabat2 2.12.1
    - numpy 1.10.4
    - pandas 0.23.4
    - perl 5.26.2
    - perl-bioperl 1.6.924
    - perl-threaded 5.22.0
    - pplacer 1.1.alpha17
    - prokka 1.*
    - qt 4.8.5
    - quast 4.*
    - readline 6.2
    - r-recommended 3.3.2
    - r-ggplot2 2.2.1
    - salmon 0.9.*
    - samtools 1.6
    - scikit-learn 0.20.2
    - scipy 0.17.1
    - seaborn 0.8.1
    - spades 3.*
    - srprism 2.4.24
    - subprocess32 3.2.7
    - taxator-tk 1.3.3e
    - tk 8.5.19
    - trim-galore 0.4.*
    - xorg-libxrender 0.9.10

about:
  home: https://github.com/ursky/metaWRAP
  license: MIT
  license_file: LICENSE

